universe   = vanilla
getenv     = True
executable = sub.sh
+JobFlavour           = "tomorrow"
requirements = (OpSysAndVer =?= "CentOS7")
RequestCpus = 16

log        = cond/pthat15_emb_pgoing.log
output     = cond/pthat15_emb_pgoing.out
error      = cond/pthat15_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat15_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_15 1 15 30 
queue

log        = cond/pthat30_emb_pgoing.log
output     = cond/pthat30_emb_pgoing.out
error      = cond/pthat30_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat30_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_30 1 30 50
queue

log        = cond/pthat50_emb_pgoing.log
output     = cond/pthat50_emb_pgoing.out
error      = cond/pthat50_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat50_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_50 1 50 80
queue

log        = cond/pthat80_emb_pgoing.log
output     = cond/pthat80_emb_pgoing.out
error      = cond/pthat80_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat80_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_80 1 80 120
queue

log        = cond/pthat120_emb_pgoing.log
output     = cond/pthat120_emb_pgoing.out
error      = cond/pthat120_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat120_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_120 1 120 170
queue

log        = cond/pthat170_emb_pgoing.log
output     = cond/pthat170_emb_pgoing.out
error      = cond/pthat170_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat170_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_170 1 170 220
queue

log        = cond/pthat220_emb_pgoing.log
output     = cond/pthat220_emb_pgoing.out
error      = cond/pthat220_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat220_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_220 1 220 280
queue

log        = cond/pthat280_emb_pgoing.log
output     = cond/pthat280_emb_pgoing.out
error      = cond/pthat280_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat280_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_280 1 280 370
queue

log        = cond/pthat370_emb_pgoing.log
output     = cond/pthat370_emb_pgoing.out
error      = cond/pthat370_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat370_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_370 1 370 460
queue

log        = cond/pthat460_emb_pgoing.log
output     = cond/pthat460_emb_pgoing.out
error      = cond/pthat460_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat460_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_460 1 460 540
queue

log        = cond/pthat540_emb_pgoing.log
output     = cond/pthat540_emb_pgoing.out
error      = cond/pthat540_emb_pgoing.err
arguments = files_input/pPb_8160/MC_embedded/pgoing/MC_pthat540_pgoing_embedded.txt /eos/user/d/ddesouza/JetResults/Emb_cut_pPb_540 1 540 8160
queue
