universe   = vanilla
getenv     = True
executable = sub.sh
+JobFlavour           = "tomorrow"
requirements = (OpSysAndVer =?= "CentOS7")
RequestCpus = 8

log        = cond/pthat15.log
output     = cond/pthat15.out
error      = cond/pthat15.err
arguments = files_input/pPb_8160/MC_embedded/Pbgoing/MC_pthat15_Pbgoing_embedded.txt 15 1 15 30 
queue

log        = cond/pthat30.log
output     = cond/pthat30.out
error      = cond/pthat30.err
arguments = files_input/pPb_8160/MC_embedded/Pbgoing/MC_pthat30_Pbgoing_embedded.txt 30 1 30 50
queue

log        = cond/pthat50.log
output     = cond/pthat50.out
error      = cond/pthat50.err
arguments = files_input/pPb_8160/MC_embedded/Pbgoing/MC_pthat50_Pbgoing_embedded.txt 50 1 50 80
queue

log        = cond/pthat80.log
output     = cond/pthat80.out
error      = cond/pthat80.err
arguments = files_input/pPb_8160/MC_embedded/Pbgoing/MC_pthat80_Pbgoing_embedded.txt 80 1 80 120
queue

log        = cond/pthat120.log
output     = cond/pthat120.out
error      = cond/pthat120.err
arguments = files_input/pPb_8160/MC_embedded/Pbgoing/MC_pthat120_Pbgoing_embedded.txt 120 1 120 170
queue

log        = cond/pthat170.log
output     = cond/pthat170.out
error      = cond/pthat170.err
arguments = files_input/pPb_8160/MC_embedded/Pbgoing/MC_pthat170_Pbgoing_embedded.txt 170 1 170 220
queue

log        = cond/pthat220.log
output     = cond/pthat220.out
error      = cond/pthat220.err
arguments = files_input/pPb_8160/MC_embedded/Pbgoing/MC_pthat220_Pbgoing_embedded.txt 220 1 220 280
queue

log        = cond/pthat280.log
output     = cond/pthat280.out
error      = cond/pthat280.err
arguments = files_input/pPb_8160/MC_embedded/Pbgoing/MC_pthat280_Pbgoing_embedded.txt 280 1 280 370
queue

log        = cond/pthat370.log
output     = cond/pthat370.out
error      = cond/pthat370.err
arguments = files_input/pPb_8160/MC_embedded/Pbgoing/MC_pthat370_Pbgoing_embedded.txt 370 1 370 460
queue

log        = cond/pthat460.log
output     = cond/pthat460.out
error      = cond/pthat460.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat460_pgoing_unembedded.txt 460 1 460 540
queue

log        = cond/pthat540.log
output     = cond/pthat540.out
error      = cond/pthat540.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat540_pgoing_unembedded.txt 540 1 540 8160
queue
