universe   = vanilla
getenv     = True
executable = sub.sh
+JobFlavour           = "tomorrow"
requirements = (OpSysAndVer =?= "CentOS7")
RequestCpus = 8

log        = cond/pthat15nocut.log
output     = cond/pthat15nocut.out
error      = cond/pthat15nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat15_pgoing_unembedded.txt 15 1 15 8160 
queue

log        = cond/pthat30nocut.log
output     = cond/pthat30nocut.out
error      = cond/pthat30nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat30_pgoing_unembedded.txt 30 1 30 8160
queue

log        = cond/pthat50nocut.log
output     = cond/pthat50nocut.out
error      = cond/pthat50nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat50_pgoing_unembedded.txt 50 1 50 8160
queue

log        = cond/pthat80nocut.log
output     = cond/pthat80nocut.out
error      = cond/pthat80nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat80_pgoing_unembedded.txt 80 1 80 8160
queue

log        = cond/pthat120nocut.log
output     = cond/pthat120nocut.out
error      = cond/pthat120nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat120_pgoing_unembedded.txt 120 1 120 8160
queue

log        = cond/pthat170nocut.log
output     = cond/pthat170nocutnocut.out
error      = cond/pthat170nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat170_pgoing_unembedded.txt 170 1 170 8160
queue

log        = cond/pthat220nocut.log
output     = cond/pthat220nocut.out
error      = cond/pthat220nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat220_pgoing_unembedded.txt 220 1 220 8160
queue

log        = cond/pthat280nocut.log
output     = cond/pthat280nocut.out
error      = cond/pthat280nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat280_pgoing_unembedded.txt 280 1 280 8160
queue

log        = cond/pthat370nocut.log
output     = cond/pthat370nocut.out
error      = cond/pthat370nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat370_pgoing_unembedded.txt 370 1 370 8160
queue

log        = cond/pthat460nocut.log
output     = cond/pthat460nocut.out
error      = cond/pthat460nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat460_pgoing_unembedded.txt 460 1 460 8160
queue

log        = cond/pthat540nocut.log
output     = cond/pthat540nocut.out
error      = cond/pthat540nocut.err
arguments = files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat540_pgoing_unembedded.txt 540 1 540 8160
queue
